### ISSUE TITLE
Co-dimensional simulations

### ISSUE THREAD

**Issue by sdast9** [ipc-sim/ipc-toolkit#15]
Quick question: Does this toolkit include the ability to handle co-dimensional simulations similar to Co-IPC?

**Comment by zfergus** [comment]
I am not sure if you mean can the toolkit completely perform codimensional FEM simulations like in the CIPC paper, or if the toolkit has the necessary components to implement CIPC?

This code base includes the necessary components in order to add the IPC's frictional contact model to a simulation pipeline. This includes computing the barrier potentials, smooth friction dissipative potential, and performing CCD. What the toolkit does not have is the FEM components necessary to implement codimensional FEM (FEM basis, elasticity models, and optimization framework for time-stepping). 

That being said, this toolkit contains most of the components shown in the CIPC paper. 

## Implemented

These features from the CIPC paper are already implemented.

* Support for codimensional triangle-triangle, triangle-edge, triangle-point, edge-edge, and edge-point (in 2D) frictional contact.
    * This is sufficient for standard IPC and a lot of CIPC, but misses some types of contact (see below)
* The IPC thickness model (i.e., $\eta$ offset in the barrier potential)
* CCD between codimensional triangle-triangle, triangle-edge, triangle-point, edge-edge, and edge-point (in 2D)
    * This is using the [Tight-Inclusion](https://github.com/Continuous-Collision-Detection/Tight-Inclusion) CCD method for guaranteed conservative CCD under floating-point 

## Missing Features

The following components are missing, but could be easily added (I am happy to add them).
* Support for codimensional edge-point (in 3D) and point-point contact. 
    * These are important for contactes between codim. edges with codim. points and for ontactes between particles (like in Fig. 22 "Granules on cloth" of the CIPC paper)
* Strain limiting
    * This is more on the side of FEM, but could be added to the toolkit. My only concern is it is a little out of scope.
* CCD for contacts between edge-point (in 3D) and point-point contact
    * I belive we can add these using Tight-Inclusion CCD
* Thickness offset in the CCD 
    * This can be easily through Tight-Inclusion's minimum separation CCD, but is currently not implemented.
* Additive CCD
    *  Instead we choose to Tight-Inclusion because of its guarantees

**Comment by zfergus** [comment]
Thank you for your nice comments. Adding shell and rod models to PolyFEM is something I have wanted to play with for a while, but I don't have a research project that motivates implementing it. I think it will eventually be implemented, but no timeline right now.

**Comment by zfergus** [comment]
Small update: #22 added the thickness offset in the CCD.
