### ISSUE TITLE
Questions regarding RigidIPC and GPU CCD

### ISSUE THREAD

**Issue by Ahdhn** [ipc-sim/ipc-toolkit#24]
Hi there!

Thank you for making this great library open-source with such high-quality code! 

I hope you don't mind me reaching out for some assistance. I was really excited to try out the GPU-based CCD implementation, and I was hoping to use it to speed up [RigidIPC](https://github.com/ipc-sim/rigid-ipc). However, I ran into some issues while updating the ipc-toolkit in RigidIPC, as there were a lot of changes since the last update. After resolving CMake errors, updating ipc-toolkit in RigidIPC gave me all sort of compilation errors (as shown in the screenshots). 

I would really appreciate it if you could give me some pointers on how to resolve these issues. I understand that you might not have the time to fix them yourself, but any rough summary of the code changes or insights would be incredibly helpful for me.

Thank you! 

![image](https://user-images.githubusercontent.com/3890167/218558816-ea6a163b-e0eb-40e7-be34-579db693b993.png)
![image](https://user-images.githubusercontent.com/3890167/218558889-1e57b731-629e-4e67-bc52-56b00ede99e1.png)

**Comment by zfergus** [comment]
I took a look at what needs to be done to update the toolkit in the Rigid IPC code. A lot of things changed in the toolkit that makes updating the rigid code a real hassle. Some examples:

* Files have move paths
* The entire broad-phase data structures have been refactored to work better for deformable.
    * this includes the `HashGrid` which had many of its specific functions made protected or stripped away
    * The AABB class was extended to keep track of vertex ids the box encodes. this is going to be troublesome as AABB is also used for rigid bodies in the rigid code
* The toolkit now uses a collision mesh object which would need to be built into the rigid code
* The idea of `multiplicity` was removed in favor of a more generic `weight` value

Beyond this, I am not sure the GPU CCD is going to be plug-and-play in the rigid code. The broad phase would need to be adjusted to work with rigid-body AABBs. The narrow-phase GPU algorithm is different in that it processes all linear queries in a single batch (for the best utilization of the GPU architecture). This means the nonlinear CCD would have to be ported to CUDA. I doubt with how complicated the structure of the nonlinear CCD is that you will get any major improvement from using a GPU.

I will push some of the changes I made (removed and updated some dependencies) which might make any work you do easier, but I rolled back my attempt to update the toolkit in the rigid code.

I am going to close this issue because it is really an issue on the Rigid IPC project, not the toolkit. Feel free to open an issue on the Rigid IPC repo.
