### ISSUE TITLE
Possibly inconsistent results for convergent formulation with respect to dhat?

### ISSUE THREAD

**Issue by Andlon** [ipc-sim/ipc-toolkit#41]
**Describe the bug**
I'm using `CollisionConstraints::set_use_convergent_formulation(true)` to obtain quantities that are less tessellation-dependent and that - to my understanding - vary less with the value of `dhat`.

I am not sure if perhaps I've misunderstood the true purpose of this formulation, but I'm observing inconsistent values for different values of `dhat` in a setting in which I would expect the values to be more similar.

Consider the following example. Take a squished unit tetrahedron with vertices `(0, 0, 0)`, `(1, 0, 0)`, `(0, 1, 0)` and `(0, 0, 0.5 * dhat)`. Since the z-coordinate of the "top" vertex is proportional to `dhat`, I would expect a similar potential energy value for different values of `dhat` (noting of course that changing `dhat` for this example also changes the area of the triangles).

Here's the output I get for different values of `dhat` for this example:

```
dhat = 0.0001
  Potential: 5.26234e-09
  Scaled potential: 0.526234
dhat = 0.001
  Potential: 5.26234e-07
  Scaled potential: 0.526234
dhat = 0.01
  Potential: 5.26251e-05
  Scaled potential: 0.526251
```

Since the inputs to the barrier function are squared, I believe the "real" barrier contribution works out to `-log(d^2/dhat^2) (d^2 - dhat^2)^2`. To make this unitless, we'd have to divide by `dhat^4`, however my understanding is that the `weight` constant currently used to scale the barrier function is divided by `dhat^2` (when `dmin = 0`). The `Scaled potential` in the above output refers to dividing the potential by `dhat^2`, to make up for the missing powers.

**To Reproduce**
Here's a self-contained minimal example that I used to produce the output above:
```c++
#include <ipc/ipc.hpp>
#include <iostream>
#include <array>

int main() {
    const auto dhat_values = std::array<double, 3> { 1e-4, 1e-3, 1e-2 };

    for (const auto dhat : dhat_values) {
        Eigen::MatrixXd rest_vertices(4, 3);
        rest_vertices <<
                      0.0, 0.0, 0.0,
                1.0, 0.0, 0.0,
                0.0, 1.0, 0.0,
                0.0, 0.0, 1.0;

        Eigen::MatrixXd deformed_vertices = rest_vertices;
        deformed_vertices.row(3)(2) = 0.5 * dhat;

        Eigen::MatrixXi edges(6, 2);
        edges << 0, 1,
                0, 2,
                0, 3,
                1, 2,
                1, 3,
                2, 3;
        Eigen::MatrixXi faces(4, 3);
        faces << 0, 2, 1,
                0, 1, 3,
                0, 3, 2,
                1, 2, 3;

        ipc::CollisionMesh mesh = ipc::CollisionMesh::build_from_full_mesh(rest_vertices, edges, faces);
        ipc::CollisionConstraints constraints;
        constraints.set_use_convergent_formulation(true);
        constraints.build(mesh, deformed_vertices, dhat);

        const double potential = constraints.compute_potential(mesh, deformed_vertices, dhat);
        std::cout << "dhat = " << dhat << std::endl;
        std::cout << "  Potential: " << potential << std::endl;
        std::cout << "  Scaled potential: " << potential / (dhat * dhat) << std::endl;
    }

    return 0;
}
```

**Expected behavior**
I had expected to get the value of the "scaled potential" above when using the "convergent formulation". This might however be due to a misunderstanding on my part.

**Additional context**
This is not a big deal on my part, because I can work around it by dividing by `dhat^2`, but I thought I ought to let you know, in case this is an issue that has gone undiscovered.

**Comment by zfergus** [comment]
The intention of this change is to be able to express the barrier potential in the same physical units as the elasticity potential (i.e., Pa $\cdot$ m) (more on this at the bottom). With non-squared distances, we do this by writing the barrier function as

$$
b_\text{new}(d, \hat{d}) = -\kappa\hat{d}\left(\frac{d}{\hat{d}} - 1\right)^2 \log\left(\frac{d}{\hat{d}}\right).
$$

The relationship between $b_\text{old}(d, \hat{d})$ and $b_\text{new}(d, \hat{d})$ is 

$$
b_\text{new}(d, \hat{d}) = \frac{1}{\hat{d}} b_\text{old}(d, \hat{d}).
$$

In the toolkit, we only implement $b_\text{old}(d, \hat{d})$ and store this division in the `weight` for simplicity of implementation.

However, we are using distances squared so we actually want to compute

$$
b_\text{new}(d^2, \hat{d}^2) = -\kappa\hat{d}\left(\frac{d^2}{\hat{d}^2} - 1\right)^2 \log\left(\frac{d^2}{\hat{d}^2}\right).
$$

Again the relationship between $b_\text{old}(d^2, \hat{d}^2)$ and $b_\text{new}(d^2, \hat{d}^2)$ is 

$$
b_\text{new}(d, \hat{d}) = \frac{1}{\hat{d}^3} b_\text{old}(d, \hat{d}).
$$

Again, we only implement $b_\text{old}(d, \hat{d})$, so we want to store this division in the `weight` for simplicity of implementation. However, I am dividing by $\hat{d}^2$ when I should be dividing by $\hat{d}^3$ to get the correct units. I will make this change.

This will still not produce the same behavior as you expect (because we multiply the normalized barrier by $\hat{d}$), but this is the correct implementation of the algorithm we want (i.e., physically-based units for the barrier term). Alternatively, if you wanted to use the normalized barrier, you could assume the units of $\kappa$ are Pa $\cdot$ m. What I like about the intended implementation is that $\kappa$ has units of Pa and we can express $\kappa$ as a ratio of the materials Young's modulus ($0.1E$ works well in many examples). 

The intention is to treat the barriers as a thin elastic region around the mesh, and having consistent units makes it easier to pick the stiffness for this "material".

**Comment by Andlon** [comment]
Ah, that's an interesting interpretation! Here's what I've been thinking about the value of $\kappa$ (when not being automatically determined). It should:

- be high enough so that, at *force equilibrium*, for all distances, $d^2 / \hat{d}^2 > 0.05$ (or something like that, I can't remember what a reasonable value is), i.e. we want to keep the distance in the "well-conditioned" part of the log barrier (i.e. in the part of the domain where it does not change too rapidly).
- not be so high as to cause excessive stiffness and conditioning issues in the other direction

Since we look at the ratio between $d / \hat{d}$ the $\kappa$ value should be relatively independent of choice of $\hat{d}$ (and I've observed that in some admittedly too simple experiments). But I haven't tried to vary elastic parameters yet. I think I lack the right physical intuition to understand why material stiffness impacts the "right" value of $\kappa$. Intuitively I would think that - at least for resting contacts - the stiffness does not matter so much for the relative location of the force equilibrium. I have to think about this!

Feel free to close this unless you want to track the change you said you wanted to make. I guess long term you probably also want to document what the convergent formulation actually does, but I suspect this will eventually appear in due time anyway :-)
